---
# configuration for workflow automation from https://github.com/HapagLloyd/workflow-templates
repository:
  type: github-only # docker, github-only, maven, python, terraform_module
  release: auto # auto, manual
