---
name: Lint files

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_linter_callable.yml@514cf33cb1a4e0581c00383c2b67cabf5f76f24e
    secrets: inherit
