---
name: "Pull Request"

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches-ignore:
      - "release-please--branches--*"

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_pull_request_callable.yml@b8306b5844712e1108311f3de60a3ac79534b572
    secrets: inherit
