---
name: Release Test

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - release-dry-run

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/maven_release_dry_run_callable.yml@b8306b5844712e1108311f3de60a3ac79534b572
    secrets: inherit
