---
name: Release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/maven_release_callable.yml@48d922624b9ea3f00a1ccc7323695eace961e5cb
    secrets: inherit
