---
name: Release Test

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - release-dry-run

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/maven_release_dry_run_callable.yml@48d922624b9ea3f00a1ccc7323695eace961e5cb
    secrets: inherit
