---
name: Release Test

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - release-dry-run

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/semantic-release-dry-run.yml@514cf33cb1a4e0581c00383c2b67cabf5f76f24e
    secrets: inherit
