---
name: "Check spelling"

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_spelling_callable.yml@b8306b5844712e1108311f3de60a3ac79534b572
    secrets: inherit
