---
name: "Close stale issues and PRs"

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "25 2 * * *"

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_stale_callable.yml@b8306b5844712e1108311f3de60a3ac79534b572
    secrets: inherit
